version: '3'

services:
  postgres:
    image: 'postgres:16.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shorturl
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    networks:
      default:
        aliases:
          - postgres