# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: | 
        go mod tidy

    - name: Build
      run: |
        cd cmd/shorturl
        go build -o ../../shorturl

    - name: Test    
      run: |
        go test -v ./...

    - name: Deploy 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST}}
        username: ${{ secrets.USERNAME}}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT}}
        script: 
          echo Starting deployment for ShortURL
          echo Pulling from Github...
          cd #
          cd shorturl
          git pull
          echo Building ShortUrl...
          cd shorturl/cmd/shorturl
          go build -o ../../shorturl
          echo Restarting Service...
          sudo systemctl restart shorturl-service.service

